### ISSUE TITLE
不能生成正确的auth_url

### ISSUE THREAD

**Issue by jesset** [yfli/twitter-to-weibo-appengine#7]
http://jesses-t2w.appspot.com

用的是当前master分支

麻烦看看，谢谢

**Comment by yfli** [comment]
你更改myid.py中twitter API KEY 和API SECRET为你自己api的key和secret了吗？

**Comment by jesset** [comment]
都改过了，截图如下

![Screen Shot 2013-04-02 at 11 16 01](https://f.cloud.github.com/assets/56474/329004/be6d8d78-9ba8-11e2-920e-2044d5983aab.png)

**Comment by yfli** [comment]
能不能把app的log给我看看。应该会输出Error级别的log

**Comment by jazzpasta** [comment]
我也不能生成正确的url

URLFetch request: ['Host']
INFO     2013-06-06 07:41:00,414 server.py:585] default: "GET / HTTP/1.1" 200 697
INFO     2013-06-06 07:41:01,922 server.py:585] default: "GET /favicon.ico HTTP/1.1" 404 154
INFO     2013-06-06 07:41:05,973 server.py:585] default: "GET /%7B%7Bauth_url%7D%7D HTTP/1.1" 404 154
INFO     2013-06-06 07:41:06,528 server.py:585] default: "GET /favicon.ico HTTP/1.1" 404 154

结果是在template理的home.html url里的{" and "}" turn into "%7B" and "%7D"，不知道是不是Mac系统的关系
问题解决

**Comment by yfli** [comment]
这个问题上次已经解决了，你更新到最新的code
